version: '3.1'
services:
  stats-server:
    build: stats-server/stats-service
    container_name: stats_server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_STATS=jdbc:postgresql://statsdb:5432/explore
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STATS_SERVER_URL=http://stats-db:9090

  stats-db:
    image: postgres:14-alpine
    container_name: db_stats
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/dataStats
    environment:
      - POSTGRES_DB=exploreStats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-server:
    build: main-server
    container_name: main_server
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - MAIN_SERVER_URL=http://mainserver:8080
      - SPRING_DATASOURCE_MAIN=jdbc:postgresql://ewm-db:5432/explore
      - POSTGRES_USER_MAIN=root
      - POSTGRES_PASSWORD_MAIN=root

  ewm-db:
    image: postgres:14-alpine
    container_name: main_server_db
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/dataMain

    environment:
      - POSTGRES_DB=exploreMain
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
